### ISSUE TITLE
Build fails on Ubuntu (can't import QApplication)

### ISSUE THREAD

**Issue by jshumakerpruitt** [Automattic/mShots#5]
The location of QtWidgets doesn't match the value `binding.gyp`

```
root@server:/opt/mshots# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.5.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/mshots/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/mshots',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/opt/mshots/build'
  CXX(target) Release/obj.target/snapper/src/main.o
../src/main.cc:25:34: fatal error: QtWidgets/QApplication: No such file or directory
 #include <QtWidgets/QApplication>
                                  ^
compilation terminated.
make: *** [Release/obj.target/snapper/src/main.o] Error 1
make: Leaving directory `/opt/mshots/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/mshots
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

```
root@server:~# find /usr -name QApplication
/usr/include/qt5/QtWidgets/QApplication
```

```
root@server:/opt# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

**Comment by thelonious89** [comment]
I'm getting similar errors. I tried it on Ubuntu first and then switched to CentOS, and both gave me similar errors for QtWidgets. Any thoughts on a workaround?

**Comment by anhntbk08** [comment]
Same here, can you please fix this?

**Comment by iPixel8** [comment]
I know this may be a little outdated or you've given up, but edit the binding.gyp file to reflect the correct paths to the Qt modules and then run `sudo node-gyp configure ` as well as `sudo node-gyp build` until all paths work.

**Comment by darthhexx** [comment]
Thanks @iPixel8, that would indeed fix the Qt requirements assuming the development headers were installed. Although, as of #8, The app has been moved over to using puppeteer, so Qt is no longer required. Installation is as simple as running `npm install`. See the updated README for details.

**Comment by darthhexx** [comment]
You do not have to run any `node-gyp` commands anymore. See the README for the new installation process. It's basically just `npm install` now.

I left the `binding.gyp` and custom node backend C++ code in `/src/` in case someone wants access to the latest bug fixes in the code we have been running in production. Do yo specifically want to run the Qt version of the app?

**Comment by darthhexx** [comment]
I removed all the unnecessary gumph in #10 #11 #12  to fix the issues.
